config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  root to: 'cats#index'
  resources :cats, only: [:index] do
    post :serve, on: :collection
  end

end

app/models/cat_request.rb
class CatRequest < ActiveRecord::Base
  def fulfill!
    Cats.display! link
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cat_requests

  def cat_me!
    cat_request = cat_requests.create! link: Cats.sample
    cat_request.fulfill!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def serve
    @incoming = true
    CatJob.perform_later current_user.id
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class name
    case name
    when :notice
      :success
    when :alert
      :error
    else
      name
    end
  end
end

app/views/cats/index.html.erb
<div class="inner">
  <div class="max-width">
    <div class="cta">
      Push butan. Receive kitteh.
      <% if @incoming %>
        | Kitteh incoming. Would you like another?
      <% end %>
      <%= button_to serve_cats_path, method: :post, id: "cat_button", class: "button" do %>
          <div class="i fa fa-paw">| Cat Me</div>
      <% end %>


<% content_for :javascript do %>
  $(".inner form").submit(function() {
    $("#cat_button").
      addClass("disabled").
      attr("disabled", true).
      html("<i class='fa fa-spinner fa-spin'></i>Herding Cats…");
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeeme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Open+Sans:300,400" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <div class="flash">
        <% flash.each do |name, msg| %>
          <div class="alert alert-#{flash_class name}">
            <a class="close" data-dismiss="alert">
              <div id="flash_#{flash_class name}">
                <%= msg %>
              </div>
            </a>
          </div>
        <% end %>
      </div>
    </div>


<%= yield %>

</body>
</html>